language: node_js
node_js:
  - 0.10
env:
  - global:
    - GIT_COMMITTER_NAME=minodisk
    - GIT_COMMITTER_EMAIL=daisuke.mino@gmail.com
    - GIT_AUTHOR_NAME=minodisk
    - GIT_AUTHOR_EMAIL=daisuke.mino@gmail.com
    - secure: "gbD6PSs5eBbZU0jcQtOTkcgAFukl3+CPl8LggTGK1oNETAn85VYprSVBwhGIk9ruyQJpInBCulAcsIyi9cnFQDS6KadvHNnV28cu2Nfoqiiiac+zlXzmkMuguwsjfv4Qwxu4bqa3piyn4nQuafONoDUUWgAmOa3NqNfSVpBknaw="
after_success:
  - npm run coveralls
  - git clone -b gh-pages https://github.com/trymore/pencil.git doc
  - npm run codo
  - cd doc
  - git add -A
  - git commit -m 'Generate documents.'
  - 'git push https://$GH_TOKEN@github.com/trymore/pencil.git'
